# Generated by Django 4.1.4 on 2022-12-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_offer_created_alter_request_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
